// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7Ry43X9TuzwtudPnfLjd_TFMJbxAnBQ',
    appId: '1:965432110790:web:7169bfe0631e27bcfbb1c7',
    messagingSenderId: '965432110790',
    projectId: 'clubone-7d0ac',
    authDomain: 'clubone-7d0ac.firebaseapp.com',
    storageBucket: 'clubone-7d0ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjZib143VOVW14gop3v0XWw9zf8CJpk5E',
    appId: '1:965432110790:android:64882ee376115ba1fbb1c7',
    messagingSenderId: '965432110790',
    projectId: 'clubone-7d0ac',
    storageBucket: 'clubone-7d0ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQOezWae9Mx_m-HvwO_FNMNpcQjBbmKBE',
    appId: '1:965432110790:ios:2ed580e6d13e2e9cfbb1c7',
    messagingSenderId: '965432110790',
    projectId: 'clubone-7d0ac',
    storageBucket: 'clubone-7d0ac.appspot.com',
    iosClientId: '965432110790-m2ie96ecqig7eodeb4b9ed9nifroecoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClub',
  );
}
